apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cataloging-statistics.fullname" . }}-configmap
  namespace: cataloging-statistics{{ .Values.django.env.run_env }}
  labels:
    {{- include "cataloging-statistics.labels" . | nindent 4 }}
data:
  DJANGO_RUN_ENV: {{ .Values.django.env.run_env }}
  DJANGO_DEBUG: {{ .Values.django.env.debug | quote }}
  DJANGO_ALLOWED_HOSTS: {{ range .Values.django.env.allowed_hosts }}{{ . | quote }}{{ end }}
  DJANGO_CSRF_TRUSTED_ORIGINS: {{ range .Values.django.env.csrf_trusted_origins }}{{ . | quote }}{{ end }}
  DJANGO_DB_BACKEND: {{ .Values.django.env.db_backend }}
  DJANGO_DB_NAME: {{ .Values.django.env.db_name }}
  DJANGO_DB_USER: {{ .Values.django.env.db_user }}
  DJANGO_DB_HOST: {{ .Values.django.env.db_host }}
  DJANGO_DB_PORT: {{ .Values.django.env.db_port | quote }}
  DJANGO_LOG_LEVEL: {{ .Values.django.env.log_level }}

